import puppeteer from "puppeteer-core";
const BASE = process.argv[2] ?? "http://localhost:3000";
const OUT = process.argv[3] ?? ".";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: "new", args: ["--no-sandbox", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const page = await browser.newPage();
await page.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true });
await page.goto(BASE, { waitUntil: "domcontentloaded" });
await sleep(1800);
await page.screenshot({ path: `${OUT}/z-boot.png` });
const nav = await browser.newPage();
await nav.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true });
await nav.evaluateOnNewDocument(() => sessionStorage.setItem("csau-gate-seen", "true"));
await nav.goto(BASE, { waitUntil: "load" });
await sleep(2500);
await nav.click('button[aria-label="Open navigation"]');
await sleep(700);
await nav.evaluate(() => document.querySelector('a.ln-link[href="/events"]')?.click());
await sleep(2200);
await nav.screenshot({ path: `${OUT}/z-jump.png` });
await browser.close();
